# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b5794d5ff7a7048a685c8b5249c553f343e9b73f2462e979a5de0bfb9421ea96ac2521f32c0fac26723c32f2c77ead1f80fc77e603a44718073059b533eafe9

test:
  secret_key_base: 10994699c7e35826f0bcae06493f2c1a7b97489af6f7666dce72ce789144885144b4b5f70896655b0b710b3217e016674af2fa0b95ce8128426008660c5ec876

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
